### ISSUE TITLE
vuepress中配置后无效 且没有错误信息

### ISSUE THREAD

**Issue by gitldy1013** [francoischalifour/medium-zoom#144]
我的配置如下：

 plugins: {
        '@vuepress/medium-zoom': true
    },

**Comment by francoischalifour** [comment]
It seems like this issue is related to the Vuepress integration itself. Please report it to [vuejs/vuepress](https://github.com/vuejs/vuepress).

**Comment by gitldy1013** [comment]
thanks.I've settled it.
