### ISSUE TITLE
Optional Zoom

### ISSUE THREAD

**Issue by mjshea1** [francoischalifour/medium-zoom#156]
## The problem

Is there an option when you add medium-zoom to a vuepress site to disable it on some images within the markdown?

## Solution

The ability to disable zoom on images within a vuepress site.

## Implementation

I don't have an idea of how to implement it.

**Comment by francoischalifour** [comment]
You'll need to edit the [`selector` option in the VuePress plugin](https://vuepress.vuejs.org/plugin/official/plugin-medium-zoom.html#usage), and add this `no-zoom` CSS class to the images you want to skip.

Example:

```js
module.exports = {
  plugins: {
    '@vuepress/medium-zoom': {
      selector: 'img:not(.no-zoom)',
    }
  }
}
```
