### ISSUE TITLE
Zoom not woking?

### ISSUE THREAD

**Issue by 623636245** [francoischalifour/medium-zoom#161]
Is this normal?
![GIF](https://user-images.githubusercontent.com/22848900/96668008-c49e7400-138c-11eb-8840-bd18b765a9fd.gif)
Can't room in/out....
here's my pluginConfig
```
module.exports = {
	"vuepress-plugin-medium-zoom":{
		/*图片缩放*/
        "selector": 'img',
        "delay": 1000,
        "options": {
			"margin": 24,
			"background": '#FFFFFF',
			"scrollOffset": 0,
        },
    }
}
```

**Comment by francoischalifour** [comment]
Your original image is likely not bigger than the displayed image.

Please redirect to https://github.com/vuejs/vuepress.
