### ISSUE TITLE
Img view node add location

### ISSUE THREAD

**Issue by awnawnawn** [francoischalifour/medium-zoom#162]
Can I change the position where the node is added? I want to add it to a node
![Snipaste_2020-10-26_13-12-55](https://user-images.githubusercontent.com/47672657/97136197-6fe46a00-178d-11eb-9f91-3e84045e0e8a.png)

**Comment by francoischalifour** [comment]
Hey! You can use the [`container`](https://github.com/francoischalifour/medium-zoom/blob/fb3934e562279d5ecfc9da225ae4466aad17c8b9/docs/container.md#rendering-in-a-dom-element) option for this.

**Comment by awnawnawn** [comment]
My expectation is that the rendered `<div>` and `<img>` should be placed in `#zoom-container` **instead of placed in the child nodes of `<body>`** . Did I make a mistake?
![Snipaste_2020-10-26_21-02-37](https://user-images.githubusercontent.com/47672657/97175860-1d2ba200-17cf-11eb-81a6-5892c7656fd1.png)

**Comment by francoischalifour** [comment]
Gotcha, my bad. The [zoomed image is appended to the `body`](https://github.com/francoischalifour/medium-zoom/blob/fb3934e562279d5ecfc9da225ae4466aad17c8b9/src/medium-zoom.js#L331) and there's no option for that.

Why do you need to append the image to another DOM element?

**Comment by awnawnawn** [comment]
I just want to embed it into the expected node to achieve other effects. If not, I will think of other ways, thank you
