### ISSUE TITLE
A more "React-ish" example

### ISSUE THREAD

**Issue by antoinechalifour** [francoischalifour/medium-zoom#17]
Hey there!

I feel like the React example does not feel "React-ish" enough as it is querying the DOM.

Here is how I would use it with React: https://codepen.io/antoinechalifour/pen/rGLRom

Great job!

**Comment by francoischalifour** [comment]
Hey!

You're right, I basically copied the vanilla JS into the [`componentDidMount()`](https://github.com/francoischalifour/medium-zoom/blob/master/examples/react/src/Post.js#L10) method. The reason for that is that I wanted to emulated an environment where you want to pull data from a Markdown file already containing the DOM elements. Essentially, I wanted the exact same demo as the [`javascript example`](https://github.com/francoischalifour/medium-zoom/blob/master/examples/javascript).

I should probably rename this example `react-markdown` and create another `react` example. That said, I should definitely move the "journal" feature into the state.

I'll take some time to find a good use case to demo a more React-ish example as well as some other libraries/frameworks.

Cheers!
