### ISSUE TITLE
Zoomed image appears behind the sidebar

### ISSUE THREAD

**Issue by champagnealexandre** [francoischalifour/medium-zoom#182]
## Bug description

> A clear and concise description of what the bug is.

Zoomed image appears _behind_ any existing sidebar.

I’ve tried using margins, but then the image doesn’t scale correctly on mobile.

I’ve also tried using a container, but the zoomed image appears off-screen.

## How to reproduce

> A list of the steps to reproduce the bug.

Using the following code:

```js
const images = Array.from(document.querySelectorAll("img"));
images.forEach(img => {
  mediumZoom(img, {
    margin: 0,
    scrollOffset: 40,
    background: "#fff"
  });
});
```

in a website that has a sidebar.

## Expected behavior

> A clear and concise description of what you expected to happen.

The image should appear in front of the sidebar.

## Reproducible example

For example,
<img width="1892" alt="image" src="https://user-images.githubusercontent.com/30211986/146561016-c2fe8ca1-fde7-42a3-9d6a-c3f604b831fd.png">

## Environment

 - Browser: safari 15.1
 - `medium-zoom` version: 1.0.5

**Comment by francoischalifour** [comment]
This is likely because the sidebar `z-index` value is higher than the zoomed image. We explain how to increase the `z-index` value in the [documentation](https://github.com/francoischalifour/medium-zoom#debugging).

Closing for now, feel free to reopen.

**Comment by champagnealexandre** [comment]
@francoischalifour wonderful, working fine now!

Thank you!
