### ISSUE TITLE
Not work on <img> element in markdown.

### ISSUE THREAD

**Issue by yx91490** [francoischalifour/medium-zoom#183]
## Bug description

> when I add image in html style in  markdown, like this:

```
<img src="./foo.png" style="zoom: 50%;" />
```

image can not scale.

## How to reproduce

> as above

## Expected behavior

> image can scale.

## Environment

 - Browser: chrome / 95
 - `medium-zoom` version:1.8.2

**Comment by francoischalifour** [comment]
Can you please provide a [reproduction in this sandbox](https://codesandbox.io/s/github/francoischalifour/medium-zoom/tree/master/examples/vanilla)? Thanks

**Comment by yx91490** [comment]
> Can you please provide a [reproduction in this sandbox](https://codesandbox.io/s/github/francoischalifour/medium-zoom/tree/master/examples/vanilla)? Thanks

I'am not best at js, but this bug can be reproduced in my blog: https://yx91490.github.io/java/maven/maven_principle.html, corresponding markdown file : https://raw.githubusercontent.com/yx91490/yx91490.github.io/gh-pages/java/maven/maven_principle.md.

this picture cannot zoom:
`document.querySelector("#app > div.theme-container > main > div.theme-default-content.content__default > img")`

this picture can zoom:
`#app > div.theme-container > main > div.theme-default-content.content__default > p:nth-child(12) > img`

Thanks.

**Comment by francoischalifour** [comment]
You're using a Medium Zoom plugin created and maintained by [vuepress-community](https://github.com/vuepress/vuepress-community) so they likely know better what's going wrong. I would recommend opening an issue on their repo 🙂

Have a good day

**Comment by yx91490** [comment]
OK, thanks!
