### ISSUE TITLE
Customize overlay

### ISSUE THREAD

**Issue by EvgeniyPanin** [francoischalifour/medium-zoom#193]
## The problem

Can i customize .medium-zoom-overlay styles? 

## Solution

I need to set z-index to overlay to it cover other items with z-index property

## Implementation

We car replace options.background property to options.backgroundStyles and pass HTMLAttributes.style object

**Comment by francoischalifour** [comment]
We explain how to override the Medium Zoom styles in the [**Debugging**](https://github.com/francoischalifour/medium-zoom#debugging) section.
