### ISSUE TITLE
Manipulation image size

### ISSUE THREAD

**Issue by anluh** [francoischalifour/medium-zoom#198]
## The problem

> There are a bunch of cases when would be nice to have an opportunity to change image width & height & scale. For now if you change sizes by CSS - the position is overridden by JS element styles, which gives a lot of display issues.

## Solution

> It would be nice to have a dynamic way to rule these CSS options.

**Comment by francoischalifour** [comment]
You can specify the exact dimension of the zoom container with the `container` option. You can read more on [**Rendering with coordinates**](https://github.com/francoischalifour/medium-zoom/blob/master/docs/container.md#rendering-with-coordinates).

Let me know how this works out for you.

**Comment by anluh** [comment]
I'm using a template, and it works weirdly with coordinates, so it doesn't help me to solve this problem.

**Comment by anluh** [comment]
My problem is that the image in a template do not take all space of the template-container. Even when I specify all this as these codepen examples https://codesandbox.io/s/github/francoischalifour/medium-zoom/tree/master/examples/facebook-template?file=/src/index.js

**Comment by anluh** [comment]
Yeah, but it would be nice to have an opportunity for ex. to scale image some more on a custom event.
But because it sets position programmatically I can't do it.

**Comment by francoischalifour** [comment]
You should be able to update the `container` option when the custom event occurs with the [`update()`](https://github.com/francoischalifour/medium-zoom#updateoptions-object-zoom) option.

**Comment by francoischalifour** [comment]
I'm closing this for now @anluh—but feel free to reopen if you can't achieve what you want to do with the proposed solution.
