### ISSUE TITLE
Not working after the page transition in Astro

### ISSUE THREAD

**Issue by Nomango** [francoischalifour/medium-zoom#203]
## Bug description

`medium-zoom` is not working after the page transition in Astro.

The reason seems to be that `style` in header is gone after page transition.

## How to reproduce

1. Use Astro and ViewTransition
2. Execute `mediumZoom` and navigate to any page
3. See error

## Expected behavior

`mediumZoom` works normally.

## Reproducible example

[Link to the bug reproduction](https://codesandbox.io/p/sandbox/serverless-breeze-5ppcht)

## Environment

 - `medium-zoom` version: 1.0.8

**Comment by francoischalifour** [comment]
This isn't a problem with Medium Zoom but rather with the Astro page transition lifecycle?

**Comment by Nomango** [comment]
[Astro documentation](https://docs.astro.build/en/guides/view-transitions/#client-side-navigation-process) mentions that

> The contents of the \<head\> are swapped out inside the startViewTransition callback

and also

> Module scripts are only ever executed once because the browser keeps track of which modules are already loaded. For these scripts, you do not need to worry about re-execution.

So that the injected css disappears after cleaning \<head\> during page transition.

Should there be a way to re-inject css?

**Comment by francoischalifour** [comment]
I see. Ideally we would expose another JS bundle without injected styles, and another CSS dist file that you would import yourself.

**Comment by francoischalifour** [comment]
Would you be interested in contributing to this?

**Comment by Nomango** [comment]
Of course! But... my front-end skills are not good. Actually, I can only understand what you mean but have no idea about how to implement it. 😂 Sorry.

If you don't have much time on it, I am willing to give it a try, but it may take some time.
