### ISSUE TITLE
IE11 Support?

### ISSUE THREAD

**Issue by NewJenk** [francoischalifour/medium-zoom#26]
Great script!

But it doesn't seem to be working on IE11; also displaying this message in the console log: Exception thrown and not caught

Do you plan to support it?

**Comment by francoischalifour** [comment]
Hi! This lib is taking advantage of modern browser features. I don't have the tools and desire to support IE11, sorry!

If you *need* to support IE11, you may want to polyfill these 2 methods:

* [`Array.from()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)
* [`Array.prototype.includes()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

Please keep in mind that I might release new features introducing new incompatibilities with old browsers.
