### ISSUE TITLE
Support retina-sized img set in srcset attribute

### ISSUE THREAD

**Issue by charlie5188** [francoischalifour/medium-zoom#3]
There are mainly 2 ways of setting images for different dpi: one is CSS background with media query, the other is `srcset` attribute with `<img>`. 

Is it possible to show alternative image that are set in srcset when zooming?

**Comment by francoischalifour** [comment]
Nice idea! This feature has not yet been implemented. I won't have time to code it for the time being. Feel free to send a PR though.

**Comment by francoischalifour** [comment]
Hi @charlie5188, could you please provide more details and a specific use case for this enhancement? Also, how would you like to use this feature as a user of the library?

I'll see if it doesn't make the code too complex.

**Comment by francoischalifour** [comment]
Went for solution #6, fixed with #21.
