### ISSUE TITLE
Vue example?

### ISSUE THREAD

**Issue by aft3rlife** [francoischalifour/medium-zoom#30]
Currently, medium-zoom has examples for React. I think an example with Vue would be nice as well, cheers!

**Comment by francoischalifour** [comment]
Hi, thanks for requesting. I'm not very proficient with Vue but I guess that would be a way to do it:

<details>
<summary><code>style</code></summary>

```css
#container {
  width: 800px;
  margin: auto;
}

img {
  max-width: 100%;
}
```
</details>

<details>
<summary><code>body</code></summary>

```html
<div id="container">
  <img
    src="https://images.unsplash.com/photo-1486334803289-1623f249dd1e?auto=format&fit=crop&w=1920&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D"
    alt="Image"
  >
</div>
```
</details>

<details open>
<summary><code>script</code></summary>

```js
new Vue({
  container: '#container',
  created() {
    mediumZoom('#container img')
  }
})
```
</details>

Do you think of a better way to do it with Vue? I wouldn't like to expose bad examples.

Thanks!

**Comment by tuelsch** [comment]
I'd use the `mounted()` lifecycle hook, as it guarantees the elements being present in the DOM. https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram

```javascript
new Vue({
  container: '#container',
  mounted() {
    mediumZoom('#container img')
  }
})
```

**Comment by francoischalifour** [comment]
Thank you @tuelsch!

**Comment by johnpyp** [comment]
Is it possible to make mediumZoom work with dynamically loaded images/dom elements?

**Comment by francoischalifour** [comment]
See #24 for a similar question.

It should be possible, depending on your use case. If you're looking for an `attach()` method, there is none at the moment.
