### ISSUE TITLE
NPM / dist update

### ISSUE THREAD

**Issue by Loac-fr** [francoischalifour/medium-zoom#31]
Hey there, thanks for the library ! 

Unfortunately I wanted to use the new template function but it seems that the dist folder and npm registry are not up to date with the latest functionalities.

Should I use the source file for now or is an update planned ? 
Thanks !

**Comment by francoischalifour** [comment]
Hey, the library blew up recently, I wasn't feeling very confident in shipping this new feature. Happy to hear that you need it, that's a confidence boost! I'll make sure that I've tested it enough (should be fine!) and will publish the new release in the week 🙂

If you don't mind, can you share what you plan to use the `template` option for?

**Comment by francoischalifour** [comment]
Released with 0.3.0. You can upgrade to get the `template` feature.
