### ISSUE TITLE
overlay and image divs appended before closing body tag

### ISSUE THREAD

**Issue by selfagency** [francoischalifour/medium-zoom#37]
so this is weird—

```javascript
      mediumZoom('[data-action="zoom"]', {
        container: ('#zoom-container'),
        background: bgColor,
        margin: 40
      })
```

when i click on an image, my specified container is completely ignored and the overlay and image are inserted before the closing body tag. the image is also repeated twice.

![screenshot 2018-02-22 21 41 52](https://user-images.githubusercontent.com/2541728/36575548-7f171cfa-1819-11e8-9d10-b34012a2b2d0.png)

**Comment by francoischalifour** [comment]
Hi @selfagency, did you style your `#zoom-container`? You need to specify its dimensions with CSS attributes. Also, note that you don't need the parentheses around your selector.

If you need further support, please provide a reproducible example on [Codepen](https://codepen.io/) for example.
