### ISSUE TITLE
HD image doesn't scale the first time on Firefox

### ISSUE THREAD

**Issue by mimamuh** [francoischalifour/medium-zoom#38]
Hi, 

I found a issue on FF 58 (not sure if it applies for later versions too). When I use a `data-zoom-target` for my image and click it – on the first click medium zoom does not scale the image up to the size of the dynamic loaded image instead it uses the smaller dimensions of the `src` image. 

On the second click it uses the proper dimensions.

Reproduction:
Code: [Codesandbox.io](https://codesandbox.io/s/ry5plrqjp) 
Example page to test: [page](https://ry5plrqjp.codesandbox.io/)

**Comment by francoischalifour** [comment]
Hi @MiMaMuh, thanks for reporting. The HD feature will be rethought and reimplemented from scratch at some point, see #27. I can't tackle this for now though.

**Comment by rawthriver** [comment]
Subscribing. Like this plugin. Great if this issue will be fixed.

**Comment by francoischalifour** [comment]
:tada: Medium Zoom 1.0.0 fixes this bug @mimamuh and @rawthriver!

[Check the release →](https://github.com/francoischalifour/medium-zoom/releases/tag/1.0.0)
