### ISSUE TITLE
[suggestion] add mousedown/touch feedback

### ISSUE THREAD

**Issue by simonhermann** [francoischalifour/medium-zoom#57]
It would be great to have some feedback when clicking/tapping the image.
Essentially what the CSS :active pseudo class does, but unfortunately it is not available on img tags.
Usually images are passive elements, so that's okay, but with this great script they become active.

My idea was adding a class like `medium-zoom-image--active` with js `mousedown` and removing it on `mouseup` - essentially imitating :active. Don't know if that's the best solution though.

What do you think?

**Comment by simonhermann** [comment]
false alarm. 
:active actually does work on img. sorry!

**Comment by francoischalifour** [comment]
Glad you found a solution to your issue!
