### ISSUE TITLE
Angular example?

### ISSUE THREAD

**Issue by mathisGarberg** [francoischalifour/medium-zoom#58]
I've seen examples in both Vue and React, but Angular is missing. Is it possible to use Medium-zoom in Angular? Would be great!

**Comment by francoischalifour** [comment]
I'm not proficient with Angular but you can find [this example I built on CodeSandbox](https://codesandbox.io/s/lly4y7kz5q). Check `src/app/app.component.ts`.

```javascript
import { Component } from '@angular/core'
import * as mediumZoom from 'medium-zoom'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'CodeSandbox'

  ngAfterViewInit() {
    mediumZoom('img')
  }
}
```

Hope this helps!

**Comment by francoischalifour** [comment]
Did you install `medium-zoom` in your project?

```sh
npm install medium-zoom
```

**Comment by mathisGarberg** [comment]
Yes. I used `npm install --save medium-zoom`.

**Comment by andreyhideki** [comment]
i'm test including in my project and have this same error ERROR TypeError: mediumZoom is not a function.
