### ISSUE TITLE
make SUPPORTED_FORMATS part of options

### ISSUE THREAD

**Issue by karimhossenbux** [francoischalifour/medium-zoom#7]
It would be awesome if we could set SUPPORTED_FORMATS as we need.

Right now medium-zoom is enable on some SVG icons I have even if I target img tag:
`mediumZoom(document.querySelectorAll('.content img'))`

Let me know what you think?

Cheers!

**Comment by francoischalifour** [comment]
That's interesting, thanks for pointing that out!

Can you please share your HTML template?

**Comment by karimhossenbux** [comment]
Actually I've been able to fix that by targeting the parent container, and not the img tag itself.
I'll try to make more test once back on that project!

**Comment by francoischalifour** [comment]
Hi @karimhossenbux, a similar issue was raised #8.

It is indeed a bug and I will publish a fix very soon (https://github.com/francoischalifour/medium-zoom/issues/8#issuecomment-305030768).

Thank you again 😄

**Comment by francoischalifour** [comment]
Closing for now as it should be fixed with aa8ff0f.

Please upgrade to 1.0.4 and let me know if you have other issues.
