### ISSUE TITLE
1.0 intercepts all click events

### ISSUE THREAD

**Issue by rungta** [francoischalifour/medium-zoom#71]
On upgrading to the recently released 1.0 version, regular links have stopped working.

## How to reproduce

1. Add a link to a URL somewhere in your HTML
1. Run `mediumZoom('img')`
1. Click on the link
1. Page does not navigate to the URL

## Reproducible example

https://codesandbox.io/s/r7rw0qr6l4

## Environment

 - Browser: Chrome
 - `medium-zoom` version: 1.0.0

**Comment by francoischalifour** [comment]
Fix released in 1.0.1. Thank you for reporting!
