### ISSUE TITLE
Destroy/stop method

### ISSUE THREAD

**Issue by chrisjansky** [francoischalifour/medium-zoom#91]
Hello,
nice work on this library! I am looking for a way to stop the plugin from firing more events right after opening the zoom window — I'll fade it out and destroy manually after a new page is loaded in the background.

Something like:
```javascript
zoom.on('open', function() {
  zoom.off('open');
  }, {
  once: true
});
```

I tried detaching, but that "too cleverly" closes the modal before that, I really just want it to stop listening to any events (and stay opened).

Thanks.

**Comment by francoischalifour** [comment]
Can you please explain what feature you're trying to build (the _why_)? Checking if we can find a workaround with the current API.

**Comment by chrisjansky** [comment]
Here's a screencapture of what I needed to accomplish: https://www.dropbox.com/s/s4i4337kr6tv4pd/zoom-page-transition.mp4?dl=0

Basically use medium-zoom as a page transition, once the zoom is opened, destroy the instance and remove the HTML in a clean manner and show the new page that loaded beneath.

I ended up coding it myself, so you may close this issue if you think the API does not need change to allow things like this.

Thanks!
